version: "3.9"


services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"


  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis


  worker:
    build: .
    command: celery -A worker.celery_app worker --loglevel=info -Q qa_queue
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0